### ISSUE TITLE
【Q009】如何实现一个元素的水平垂直居中

### ISSUE THREAD

**Issue by shfshanyue** [shfshanyue/Daily-Question#10]

**Comment by woohs** [comment]
绝对定位方法：
```
.box {
  postion: absolute;
  top: 50%;
  bottom: 50%;
  width: 50px;
  height: 50px;
  transform: translate(-50%, -50%);
}
<body>
<div class="box"><div>
</body>
```

flex方法：
```
body {
    display: flex;
    justify-content: center;
    align-items: center;
}
.box {
  width: 50px;
  height: 50px;
}

<body>
<div class="box"><div>
</body>
```

**Comment by shfshanyue** [comment]
提供一个较少提过的方法，使用 `grid`，它是做二维布局的，但是只有一个子元素时，一维布局与二维布局就一样了。结合 `justify-content`/`justify-items` 和 `align-content/align-items` 就有四种方案

效果可以见 [codepen](https://codepen.io/shanyue/pen/ZEERzzL)

``` css
.container {
  display: grid;
  justify-content: center;
  align-content: center;
}
```


``` css
.container {
  display: grid;
  justify-content: center;
  align-items: center;
}
```


``` css
.container {
  display: grid;
  justify-items: center;
  align-content: center;
}
```


``` css
.container {
  display: grid;
  justify-items: center;
  align-items: center;
}
```
