### ISSUE TITLE
【Q017】css 如何实现左侧固定300px，右侧自适应的布局

### ISSUE THREAD

**Issue by shfshanyue** [shfshanyue/Daily-Question#18]

**Comment by zhaochongzi** [comment]
css---
 .box{
            width:100%;;
            height:100%;
            display:flex;
        }
        .one{
            width:300px;
            height:300px;
            background-color: #afa;
        }
        .two{
            flex:1;
            height:300px;
            background-color: #ae5aca;
        }
html----
 <div class="box">
        <div class="one">12312313</div>
        <div class="two">123</div>
    </div>

**Comment by shfshanyue** [comment]
使用 `flex` 布局，左侧 `330px`，右侧 `flex-grow: 1`

**Comment by Uwah** [comment]
左侧300px；右侧flex: 1; 采用flex的固比模型

**Comment by bohancen** [comment]
使用calc方法
.left{width:330px;}
.right{width: calc(100% - 330px)}

**Comment by wuzqZZZ** [comment]
浮动+BFC

```html
<div class="box">
  <div class="box1"></div>
  <div class="box2"></div>
</div>
```

```css
.box {
    height: 400px;
    background-color: skyblue;
}
.box1 {
    float: left;
    width: 100px;
    height: 100px;
    background-color: red;
} 
.box2 {
    height: 200px;
    background-color: blue;
   overflow:hidden;
}
```
