### ISSUE TITLE
【Q190】使用 CSS 如何画一个三角形

### ISSUE THREAD

**Issue by shfshanyue** [shfshanyue/Daily-Question#191]

**Comment by Sumarina** [comment]
`
.triangle {
    width: 0px;
    height: 0px;
    border: 100px solid;
    border-color: transparent transparent rgba(134, 241, 143,1) transparent;
}
`

**Comment by senking2** [comment]
`.container{
width: 0; height:0;
border-color: transparent;
border-left: 100px solid #f00;
}`

**Comment by Innocentw** [comment]
```
    .triangle {
      width: 0;
      border: 100px solid transparent;
      border-bottom: 100px solid rgba(66, 142, 212, 0.4);
    }
```

**Comment by cy948** [comment]
```css

        .triangle {
            margin: 0 auto;
            width: 50vh;
            height: 50vh;
            background-color: aqua;
            /* 
                画多边形： 
                polygon(x y, x y, ...)
                一组 x y, 代表一个点
                x: 往右增加
                y: 往下增加
            */
            clip-path: polygon(0 0, 50% 50%, 100% 50%, 100% 100%);
        }

```

![image](https://user-images.githubusercontent.com/67412196/168428324-a5bd20c9-b2f9-4bf9-9139-5aa21f142c58.png)
