### ISSUE TITLE
【Q282】对一个非定长宽的块状元素如何做垂直水平居中

### ISSUE THREAD

**Issue by shfshanyue** [shfshanyue/Daily-Question#284]

**Comment by huxiamei** [comment]
flex布局

**Comment by XJHxjh0118** [comment]
定位
`
.parent{
  position: relative;
}
.child{
  position: absolute;
  top: 50%;
  left: 50%;
 transform: translate(-50%, -50%);
}
`

**Comment by im70kg** [comment]
css position
```
        .container {
            position: relative;
        }
        .container .item {
            width: 100px;
            height: 50px;
            position: absolute;
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
            margin: auto;
        }
```

**Comment by shfshanyue** [comment]
> css position
> 
> ```
>         .container {
>             position: relative;
>         }
>         .container .item {
>             width: 100px;
>             height: 50px;
>             position: absolute;
>             top: 0;
>             left: 0;
>             bottom: 0;
>             right: 0;
>             margin: auto;
>         }
> ```

非定宽了，你这个不行呀

**Comment by jkLennon** [comment]
https://github.com/shfshanyue/Daily-Question/issues/10

**Comment by wuzqZZZ** [comment]
```html
<div class="parent">
  <div class="child">123456</div>
</div>
```
```css
.parent {
  display: flex;
  height: 200px;
  background-color: #222;
}

.child {
  background-color: red;
  margin: auto;
}
```

**Comment by LIyu2001** [comment]
```css
---方法一:父级flex
.container{
  display: flex;
  justify-content: center;
  align-items: center;
}

---方法二：父级grid
.container{
  display: grid;
  justify-content: center;
  align-items: center;
}


---方法三：父级定位，子maigin
.container{
  position: relative;
}

.container .item{
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  margin: auto;
}

---方法四：父级定位，子位移
.container{
  position: relative;
}

.container .item{
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%,-50%);
}
```
