### ISSUE TITLE
【Q306】如何实现左右固定，中间自适应布局

### ISSUE THREAD

**Issue by shfshanyue** [shfshanyue/Daily-Question#308]

**Comment by shfshanyue** [comment]
可以参考 [【Q017】css 如何实现左侧固定300px，右侧自适应的布局](https://github.com/shfshanyue/Daily-Question/issues/18)


``` pug
.container
  .left
  .main
  .right
```

``` css
.container {
  display: flex;
}

.left {
  flex-basis: 300px;
  flex-shrink: 0;
}

.right {
  flex-basis: 300px;
  flex-shrink: 0;
}

.main {
  flex-grow: 1;
}
```
