### ISSUE TITLE
【Q307】如何实现表格单双行条纹样式

### ISSUE THREAD

**Issue by shfshanyue** [shfshanyue/Daily-Question#309]

**Comment by shfshanyue** [comment]
通过 `css3` 中选择器 `:nth-child` 来实现

``` css
tr:nth-child(2n) {
  background-color: red;
}


tr:nth-child(2n+1) {
  background-color: blue;
}
```

**Comment by nanwangjkl** [comment]
不是有odd和even吗
```css
tr:nth-child(even) {background: #CCC}
tr:nth-child(odd) {background: #FFF}
```
