### ISSUE TITLE
【Q465】css 如何实现响应式布局大屏幕三等分、中屏幕二等分、小屏幕一等分

### ISSUE THREAD

**Issue by shfshanyue** [shfshanyue/Daily-Question#473]

**Comment by shfshanyue** [comment]
使用 Grid 布局可以轻松解决这个问题:

``` html
<div class="container">
  <div class="item"></div>
  <div class="item"></div>
  <div class="item"></div>
  <div class="item"></div>
  <div class="item"></div>
  <div class="item"></div>
</div>
```

``` css
@media (min-width: 1024px) {
  .container {
    grid-template-columns: repeat(3,minmax(0,1fr));
  }
}

@media (min-width: 768px) {
  .container {
    grid-template-columns: repeat(2,minmax(0,1fr));
  }
}

.conainer {
  display: grid;
  grid-gap: 1rem;
  gap: 1rem;
}
```

``` html
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4"></div>
```
