### ISSUE TITLE
【Q469】HTML 中的 input 标签有哪些 type

### ISSUE THREAD

**Issue by shfshanyue** [shfshanyue/Daily-Question#477]

**Comment by shfshanyue** [comment]
以下是关于 type 的表格，并显示是否为 HTML5 新加

``` yaml
- Type: button
  Code: <input  type="button" name="button" />
  Spec: 
- Type: checkbox
  Code: <input  type="checkbox" name="checkbox"/>
  Spec: 
- Type: color
  Code: <input  type="color" name="color"/>
  Spec: HTML5
- Type: date
  Code: <input  type="date" name="date"/>
  Spec: HTML5
- Type: datetime-local
  Code: <input  type="datetime-local" name="datetime-local"/>
  Spec: HTML5
- Type: email
  Code: <input type="email" name="email"/>
  Spec: 
- Type: file
  Code: <input type="file" accept="image/*, text/*" name="file"/>
  Spec: 
- Type: hidden
  Code: 
  Spec: 
- Type: image
  Code: <input type="image" name="image" src="" alt="image input"/>
  Spec: 
- Type: month
  Code: <input type="month" name="month"/>
  Spec: HTML5
- Type: number
  Code: <input  type="number" name="number"/>
  Spec: 
- Type: password
  Code: <input  type="password" name="password"/>
  Spec: 
- Type: radio
  Code: <input type="radio" name="radio"/>
  Spec: 
- Type: range
  Code: <input type="range" name="range" min="0" max="25"/>
  Spec: HTML5
- Type: reset
  Code: <input  type="reset" name="reset"/>
  Spec: 
- Type: search
  Code: <input  type="search" name="search"/>
  Spec: HTML5
- Type: submit
  Code: <input type="submit" name="submit"/>
  Spec: 
- Type: tel
  Code: <input  type="tel" name="tel"/>
  Spec: HTML5
- Type: text
  Code: <input type="text" name="text"/>
  Spec: 
- Type: time
  Code: <input  type="time" name="time"/>
  Spec: HTML5
- Type: url
  Code: <input type="url" name="url"/>
  Spec: HTML5
- Type: week
  Code: <input type="week" name="week"/>
  Spec: 
```
