### ISSUE TITLE
【Q471】如何自定义滚动条的样式

### ISSUE THREAD

**Issue by shfshanyue** [shfshanyue/Daily-Question#479]

**Comment by shfshanyue** [comment]
滚动条相关样式都是伪元素，以 `scrollbar` 打头，有以下伪元素，从 `-webkit` 中可见兼容性一般，不过无所谓，现在 Chrome 浏览器占大头

+   `::-webkit-scrollbar` — 整个滚动条.
+   `::-webkit-scrollbar-button` — 滚动条上的按钮 (上下箭头).
+   `::-webkit-scrollbar-thumb` — 滚动条上的滚动滑块.
+   `::-webkit-scrollbar-track` — 滚动条轨道.
+   `::-webkit-scrollbar-track-piece` — 滚动条没有滑块的轨道部分.
+   `::-webkit-scrollbar-corner` — 当同时有垂直滚动条和水平滚动条时交汇的部分.
+   `::-webkit-resizer` — 某些元素的corner部分的部分样式(例:textarea的可拖动按钮).

但其实最常用的是以下几个伪元素，滚动条设置成功

``` css
::-webkit-scrollbar {
    width: 6px;
    height: 6px
}

::-webkit-scrollbar-track {
    border-radius: 3px;
    background: rgba(0,0,0);
    box-shadow: inset 0 0 5px rgba(0,0,0,.08)
}

::-webkit-scrollbar-thumb {
    border-radius: 3px;
    background: rgba(0,0,1);
    box-shadow: inset 0 0 10px rgba(0,0,0,.2)
}
```
