### ISSUE TITLE
【Q478】如何实现容器中子元素三个三列布局，子元素两个则两列布局

### ISSUE THREAD

**Issue by shfshanyue** [shfshanyue/Daily-Question#486]

**Comment by 9527YL** [comment]
[代码演示](https://codepen.io/9527yl/pen/dyVyQJV)

css布局阔以使用`flex`，`grid`.

关健在于如何判断有多少元素。我们只需要判断有1个，有2个的情况，其他都是三列布局

```css

/* 有1个元素 */
.item:nth-last-child(1):first-child {
  flex: 1;
}

.item:nth-last-child(1):first-child ~ .item {
  flex: 1;
}

/* 有2个元素 */
.item:nth-last-child(2):first-child {
  flex: 1;
}

.item:nth-last-child(2):first-child ~ .item {
  flex: 1;
}

```
