### ISSUE TITLE
【Q758】如何实现父容器中子元素具有相同间距的分布

### ISSUE THREAD

**Issue by shfshanyue** [shfshanyue/Daily-Question#815]
布局如下图所示：

![](https://static.shanyue.tech/images/24-12-20/clipboard-0617.1986b5.webp)

**Comment by shfshanyue** [comment]
[代码见 codepen](https://codepen.io/shanyue/pen/YPKVKYJ)

对于实现该布局，有多种方案，最简单的即 flex/gap：

``` css
.container {
  display: flex;
  gap: 16px;
}
```

如果不借助 `flex` 的话，使用 `* + *` 猫头鹰选择器也是一个很好的方案：

``` css 
.container > * + * {
  margin-left: 16px
}
```

如果对 `* + *` 以及 `flex` 均不熟悉的话，也可以使用 `:not(:first-child)` 来实现

``` css
.item:not(:first-child) {
  margin-left: 16px
}
```

![](https://static.shanyue.tech/images/24-12-20/clipboard-8284.06f0d4.webp)

如果在 tailwindcss 中，可以使用以下写法：

``` html
<div class="container space-x-4" > </div>

<div class="container gap-4" > </div>
```
